### ISSUE TITLE
release-mod does not push tags

### ISSUE THREAD

**Issue by logicminds** [nwops/release_manager#9]

**Comment by mjbain151** [comment]
The issue seems limited to pushing tags upstream to the r10k repo.

**Comment by logicminds** [comment]
Seems odd that it only happens for r10k.  If r10k is treated as a module that it should work the same.  The following code is what pushes the code.  It might be a permissions issue with creating the tag upstream since the user would need permissions to create the tag.  Can you check to see if you have permission to create a tag in gitlab on r10k-control?

https://github.com/nwops/release_manager/blob/master/lib/release_manager/puppet_module.rb#L185

**Comment by mjbain151** [comment]
I agree that should be the case, but the failures so far has only being seen with r10k. Maybe we should look deeper for example "pry"  to inspect variables when tagging r10k.  We can look here...
https://github.com/nwops/release_manager/blob/master/lib/release_manager/git/utilites.rb#L129

**Comment by logicminds** [comment]
I am not able to find any issues with the code.  Are you able to reproduce this problem?

**Comment by logicminds** [comment]
closing for now as this is a non issue.  If the issue reappears please reopen.
